#!/usr/bin/env bash
# A Bash script that kills the 7-highlander process using SIGKILL

# Find all PIDs of processes whose command includes '7-highlander'
pids=$(pgrep -f 7-highlander)

# Send SIGKILL (signal 9) to each PID found
for pid in $pids; do
    kill -9 "$pid"
done
